#!/bin/bash
set -e

case "$1" in
    remove|upgrade)
        rm -f /etc/modules-load.d/kblocker.conf
        systemctl daemon-reload 2>/dev/null || true
        ;;
    purge)
        rm -f /etc/modules-load.d/kblocker.conf
        rm -rf /etc/kblocker
        rm -rf /var/lib/kblocker
        systemctl daemon-reload 2>/dev/null || true
        ;;
esac